Brent Oakes - Code Challenge Pull Request
datamade/code-challenge pull request #30
Opened 2022-08-29 23:15 UTC by boakes

## Overview

This is my Pull Request for the code-challenge. Below are some testing instructions to confirm that all requirements have been fulfilled. 

### Notes

If I had more time to work on this I would like to spend more time on error handling and make those responses have better pretty prints. 

## Testing Instructions

* How to test this PR
* Checkout this branch
* Manual test: 
* 1.  docker-compose build  
* 2.  docker-compose up
* 3. In a web browser go to: http://localhost:8000/
* 4. Test `123 main st chicago il` gets parsed to 
![image](https://user-images.githubusercontent.com/15006825/187312953-d16a349b-7709-463c-8a68-8c576ba1021a.png)
* 5. Test `123 main st chicago il 123 main st` returns an error. 
* 6. Confirm any additional addresses are parsed correctly/incorrectly 
* Automated test: docker-compose -f docker-compose.yml -f tests/docker-compose.yml run --rm app

2022-09-09 21:25 UTC, derekeder requested changes
@boakes thank you for submitting your code challenge. you did a great job organizing and testing your code.

I have a few suggested changes to make. Could you take a look and address ahead of our meeting next week?

2022-09-09 21:25 UTC, derekeder commented on parserator_web/static/js/index.js
> +        //$('#address-table').children('tbody').html(tableData);
we should remove commented out lines like these

2022-09-09 21:25 UTC, derekeder commented on parserator_web/static/js/index.js
> +        //of pretty print for error text
would you mind giving this a shot? I'd like to see what you had in mind. also, keep in mind the people using the parserator form are likely not programmers, so the output on the error message shouldn't be too technical

2022-09-09 21:25 UTC, derekeder commented on tests/test_views.py
> +    address_list = address_string.split(" ")
can you think of a way to test this using the `usaddress` library? remember, this test should be for the expected formatted output, not necessarily testing if usaddress is correct

2022-09-14 23:42 UTC, boakes commented on parserator_web/static/js/index.js
> +        //$('#address-table').children('tbody').html(tableData);
Oops! I think I removed them all now. Fixxed in [b663459](https://github.com/datamade/code-challenge/pull/30/commits/b66345992783d979e6e132eeec8762c7de4a0a9d)

2022-09-14 23:46 UTC, boakes commented on parserator_web/static/js/index.js
> +        //of pretty print for error text
I went ahead and did a simple alert box using some bootstrap css. I also made it so the full error message does still show up, but is hidden by default in an accordion card. Changed in [e299682](https://github.com/datamade/code-challenge/pull/30/commits/e2996827fbb0659c83d1b25804897c75f8a9c7cc)

2022-09-14 23:48 UTC, boakes commented on tests/test_views.py
> +    address_list = address_string.split(" ")
Is this more along the lines of what you were thinking? Changed in [81f508d](https://github.com/datamade/code-challenge/pull/30/commits/81f508d78116192920db5823481c878b131251ca)

2024-07-30 19:27 UTC, closed without merging